apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: processor-pdb
  namespace: {{ .Values.namespace.name }}
spec:
  minAvailable: {{ .Values.processor.pdb.minAvailable }}
  selector:
    matchLabels:
      app: processor
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ingestor-pdb
  namespace: {{ .Values.namespace.name }}
spec:
  minAvailable: {{ .Values.ingestor.pdb.minAvailable }}
  selector:
    matchLabels:
      app: ingestor