# Node IPs
output "node1_ip" {
  description = "Public IP of control plane node"
  value       = google_compute_instance.node1.network_interface[0].access_config[0].nat_ip
}

output "node2_ip" {
  description = "Public IP of worker node"
  value       = google_compute_instance.node2.network_interface[0].access_config[0].nat_ip
}

output "node1_internal_ip" {
  description = "Internal IP of control plane node"
  value       = google_compute_instance.node1.network_interface[0].network_ip
}

output "node2_internal_ip" {
  description = "Internal IP of worker node"
  value       = google_compute_instance.node2.network_interface[0].network_ip
}

# SSH Commands
output "ssh_node1" {
  description = "SSH command for node 1"
  value       = "ssh -i ~/.ssh/shieldops ubuntu@${google_compute_instance.node1.network_interface[0].access_config[0].nat_ip}"
}

output "ssh_node2" {
  description = "SSH command for node 2"
  value       = "ssh -i ~/.ssh/shieldops ubuntu@${google_compute_instance.node2.network_interface[0].access_config[0].nat_ip}"
}

# K3s Installation Commands
output "k3s_server_install" {
  description = "Command to install K3s server on node 1"
  value       = <<-EOF
    # Run on Node 1:
    curl -sfL https://get.k3s.io | sh -s - \
      --write-kubeconfig-mode 644 \
      --disable traefik \
      --node-name shieldops-ctrl
    
    # Then get the token:
    sudo cat /var/lib/rancher/k3s/server/node-token
  EOF
}

output "k3s_agent_install" {
  description = "Command to install K3s agent on node 2"
  value       = <<-EOF
    # Run on Node 2 (replace TOKEN with actual token from node 1):
    curl -sfL https://get.k3s.io | K3S_URL=https://${google_compute_instance.node1.network_interface[0].network_ip}:6443 K3S_TOKEN=<TOKEN> sh -s - \
      --node-name shieldops-work
  EOF
}

# Kubeconfig
output "kubeconfig_command" {
  description = "Command to get kubeconfig"
  value       = <<-EOF
    # Get kubeconfig:
    ssh -i ~/.ssh/shieldops ubuntu@${google_compute_instance.node1.network_interface[0].access_config[0].nat_ip} "sudo cat /etc/rancher/k3s/k3s.yaml" > ~/.kube/shieldops.yaml
    
    # Update server address:
    sed -i '' "s/127.0.0.1/${google_compute_instance.node1.network_interface[0].access_config[0].nat_ip}/" ~/.kube/shieldops.yaml
    
    # Use it:
    export KUBECONFIG=~/.kube/shieldops.yaml
    kubectl get nodes
  EOF
}

# Ansible Inventory (generated)
output "ansible_inventory" {
  description = "Ansible inventory YAML - save to infrastructure/ansible/inventory/hosts.yml"
  value       = <<-EOF
# ShieldOps Ansible Inventory
# Generated by Terraform - do not edit manually
# Regenerate with: terraform output -raw ansible_inventory > ../ansible/inventory/hosts.yml

all:
  children:
    k3s_cluster:
      children:
        control_plane:
          hosts:
            shieldops-ctrl:
              ansible_host: ${google_compute_instance.node1.network_interface[0].access_config[0].nat_ip}
        workers:
          hosts:
            shieldops-work:
              ansible_host: ${google_compute_instance.node2.network_interface[0].access_config[0].nat_ip}

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/shieldops
    ansible_python_interpreter: /usr/bin/python3
  EOF
}

# Quick start command
output "ansible_command" {
  description = "Command to run Ansible after generating inventory"
  value       = <<-EOF
    # Generate inventory:
    cd infrastructure
    terraform output -raw ansible_inventory > ansible/inventory/hosts.yml
    
    # Run Ansible:
    cd ansible
    ansible-playbook playbooks/site.yml
  EOF
}