apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shieldops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mdgolammafuz/shieldops.git'
    path: kubernetes/helm/shieldops
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: shieldops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true