# Values for grafana/loki

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
    path_prefix: /loki
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
  limits_config:
    retention_period: 168h
    ingestion_rate_mb: 4
    ingestion_burst_size_mb: 6
    max_streams_per_user: 1000
    max_entries_limit_per_query: 5000
  compactor:
    working_directory: /loki/compactor
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
    delete_request_store: filesystem

singleBinary:
  replicas: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# Disable microservices mode components
gateway:
  enabled: false
read:
  enabled: false
write:
  enabled: false
backend:
  enabled: false