apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: shieldops
type: Opaque
stringData:
  username: "YOUR_DB_USER"
  password: "YOUR_DB_PASSWORD"
  database-url: "postgresql://YOUR_DB_USER:YOUR_DB_PASSWORD@postgres:5432/shieldops"
